import = [
    "~/.config/alacritty/catppucin-mocha.toml"
]

[font]
# 0xProto Nerd Font
# IBM Plex Mono
# Source Code Pro
# Ubuntu Mono
# Monaspace Neon Var
normal = { family = "Monaspace Neon Var", style = "Light" }
size = 11.50 #default 11.25


[window]
dynamic_title = true # Disable this for the title below this comment to show up
title = "Alacritty" # Works only if 'dynamic_title' is disabled
dimensions = { columns = 100, lines = 30 }
opacity = 0.90 #0.85
#decorations = "None"


[cursor]
style = {shape = "Block", blinking = "On"}
thickness = 0.30


